server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschool?useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  type-aliases-package: com.czy.sboot.enity
  mapper-locations: classpath*:com.czy.mapping/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl